### ISSUE TITLE
Front View

### ISSUE THREAD

**Issue by SirNate0** [dertom95/Urho3D-Blender#10]
There seems to no longer be an option to change the "front" side of an object. Is this intentional? As best I can tell, it's now fixed to exporting 
* Blender +X -> Urho +Z
* Blender +Y -> Urho -X
* Blender +Z -> Urho +Y

Are these correct? And did I just overlook the option or has it actually been removed? And if the latter, would you consider bringing it back? Most of my models face +Y in blender, which results in them facing the wrong way in Urho (LEFT instead of FORWARD).

**Comment by dertom95** [comment]
I took it out, because my urho3d-blender-renderer only works with the default "Front View". But It actually wouldn't be a problem to bring the front-view back again. It is just commented out. Are you working on master? Or did you use the release-pack?

**Comment by dertom95** [comment]
Ok,...I reactivated the Front View again. On master and the latest release-pack.
Have fun
