### ISSUE TITLE
Install error with blender version 2.82

### ISSUE THREAD

**Issue by gonzo28** [dertom95/Urho3D-Blender#12]
I get the following error message in the screenshot when I want to activate the addon in blender.

Installing of JSON-Nodetree works.

![Screenshot_20200709_215106](https://user-images.githubusercontent.com/19701969/87084313-534c1280-c22e-11ea-8edc-1e25685b3ba9.png)

**Comment by dertom95** [comment]
Did you install pyzmq in blender's python? I guess not and you did not follow the instructions here: https://github.com/dertom95/Urho3D-Blender/wiki

I just created an instructional video how to get started: https://www.youtube.com/playlist?list=PL3dUhaUzMSSq0ngtTH6f_cj7jKKRhtzdM (still processing higher resolutions)

Hope that helps.

**Comment by gonzo28** [comment]
Yes I didn't do install pyzmq. The Video helped a lot. I'm on suse tumbleweed, so I had to find out, that suse doesn't ship blender with the python bundle. Instead blender uses the system python version. On my notebook I had du install pyzmq with su, on my desktop it did without su. I don't know why, but it works.

**Comment by dertom95** [comment]
Yes, when installing or using blender from the package management it can be tricky to find out what version is actually used or where all the corresponding folders are hidden ;) Glad you found out 👍
