### ISSUE TITLE
ImportError: cannot import name 'UrhoWriteMaterialTrees' 

### ISSUE THREAD

**Issue by iBeta666** [dertom95/Urho3D-Blender#17]
Blender 3.2 Portable Version. Windows10x64. Urho3D-Blender-master v0.9.4
First had the PIL module error. Followed the advice here:
https://github.com/dertom95/Urho3D-Blender/issues/16

Now get this:
`Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.2.0-windows-x64\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D-Blender-master\__init__.py", line 59, in <module>
    from .export_scene import SOptions, UrhoScene, UrhoExportScene, UrhoWriteMaterialTrees
ImportError: cannot import name 'UrhoWriteMaterialTrees' from 'Urho3D-Blender-master.export_scene' (C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D-Blender-master\export_scene.py)`

Could it be due to the Blender version> 3.0?

**Comment by dertom95** [comment]
No, this is not due to blender >3.0. I tested this on blender 3.2alpha and just tested on official 3.2. 

Looking at the traceback, I'm quite sure something went wrong with the installation itself. Looks like you did try to install from github-zip (as it is done with most of blender-addons) , BUT this plugin (due to some dependencies ) must be installed via the release-package( https://github.com/dertom95/Urho3D-Blender/releases ) as stated in the readme right on top.

**Comment by iBeta666** [comment]
Sorry, my bad. Dunno where that one came from, but I have tried multiple times to install the correct zip: https://github.com/dertom95/Urho3D-Blender/releases/tag/v0.9.4
I only downloaded the urho3d-blender-exporter.zip, not the urho3d-blender-cs-integration.zip.
I then installed it as usual from the Blender preferences (am running Blender as Admin).
Have just tried again and get the same error, though with different import name (NodeTreeInstance instead of UrhoWriteMaterialTrees). Maybe this is progress?

`__##current_path:C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\addon_jsonnodetree
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\blender-3.2.0-windows-x64\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 57, in <module>
    from .export_urho import UrhoExportData, UrhoExportOptions, UrhoWriteModel, UrhoWriteAnimation, \
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\export_urho.py", line 7, in <module>
    from .utils import FloatToString, WriteXmlFile, BinaryFileWriter
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\utils.py", line 21, in <module>
    from .addon_jsonnodetree import JSONNodetree
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\addon_jsonnodetree\__init__.py", line 28, in <module>
    from JSONNodetreeUtils import NodeTreeInstance
ImportError: cannot import name 'NodeTreeInstance' from 'JSONNodetreeUtils' (C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\addon_jsonnodetree-master\JSONNodetreeUtils.py)`

**Comment by iBeta666** [comment]
Thanks.
It is now loading, and can see it in Render props! 
Not sure exactly what fixed it, but I redid the steps in https://github.com/dertom95/Urho3D-Blender/issues/16 and it worked. One thing noticed was I was not connected to the net previously. This time I was and got a warning from the firewall that it was blocking Blender, so unblocked.
Is connection essential when installing the addon? Anyway, doesn't matter and this is closed. 
Thanks again for your quick help.

**Comment by dertom95** [comment]
Just for info. The firewall-warning is about that I have a urho3d-renderer-runtime (a urho3d-application) running that presents you live-preview of how the last exported scene would look like. This is connected to blender via network.

**Comment by iBeta666** [comment]
Not a problem then. I've no clue what happened, or why, just glad it did!
