### ISSUE TITLE
Apply Modifier Fails

### ISSUE THREAD

**Issue by iBeta666** [dertom95/Urho3D-Blender#18]
_Urho3D Exporter v0.9.4. Blender v3.2.0. Windows10x64. Urhosharp Android App._
I'm trying to use this to fix a jerky animation in Urhosharp from the fbx exporter (+ AssetImporter). After a month realised I'm not gonna be able to get it working, therefore your Urho3D exporter. And great news - the animations run flawlessly. The problem is that the armature is rotated 90 deg wrt. the model. In Blender there is one modifier, an armature modifier, and when I check the 'Apply modifiers'  on the exporter get the following error:

`Error: Python: Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 2122, in invoke
    return self.execute(context)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 2118, in execute
    ExecuteAddon(context, not bpy.context.scene.urho_exportsettings.showLog, self.ignore_geo_skel_anim,self.only_selected_mesh)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 5023, in ExecuteAddon
    ExecuteUrhoExport(context)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 4829, in ExecuteUrhoExport
    Scan(context, tDataList, settings.errorsMem, tOptions)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\decompose.py", line 2621, in Scan
    DecomposeMesh(scene, obj, tData, tOptions, errorsMem,obj.lodsetID>0)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\decompose.py", line 1789, in DecomposeMesh
    meshObj.data.urho_export.copyInto(mesh.urho_export)
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 1061, in copyInto
    obj_vertex.manual_uv2_idx = self.manual_uv2_idx
TypeError: bpy_struct: item.attr = val: enum "" not found in ('-1')`

I hope this is fixable, but thanks anyway for updating the exporter - it is the first sign of hope in a long while.

_Settings used:_
![Current Settings](https://user-images.githubusercontent.com/5455196/175297734-6eb737ba-c82b-42a4-b14e-aec8dd517d6f.png)

**Comment by dertom95** [comment]
Hmm,...this is actually really odd. I see where the issue is occurring but not sure why. Are you by any chance using uv2:
![image](https://user-images.githubusercontent.com/389137/175351666-addfa0dc-20e5-4dff-84d6-0e1133ce4b61.png)
I could locate some other bugs around this topic but could not reproduce this specific one. I tried to catch the error (a bit). I uploaded a new release: 
https://github.com/dertom95/Urho3D-Blender/releases/tag/v0.9.4b

Give it a try. If the error still occurs you are welcome to email me your blend-file ( thomas.trocha@gmail.com ) and I will have a look. Not so much time for reproducing the error on my own...
Not sure that will solve you 90degree problem,....if not you can try to create an empty and attach the armature to this and fix the rotation on this point (or in code) or as collection-export. 
Good luck

**Comment by iBeta666** [comment]
Thanks.  Actually I didn't have the UV checked at all:
![uv settings](https://user-images.githubusercontent.com/5455196/175358250-fcd4a21b-67e6-4148-84c2-fe7d0ceb95e1.png)
All combinations of UV checkboxes come with same error. However if 'use uv2' is checked then get a different error if 'Apply modifier' is unchecked:
`Error: Python: Traceback (most recent call last):
  File "C:\Users\Dave\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 2122, in invoke
    return self.execute(context)
  File "C:\Users\Dave\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 2118, in execute
    ExecuteAddon(context, not bpy.context.scene.urho_exportsettings.showLog, self.ignore_geo_skel_anim,self.only_selected_mesh)
  File "C:\Users\Dave\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 5023, in ExecuteAddon
    ExecuteUrhoExport(context)
  File "C:\Users\Dave\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 4829, in ExecuteUrhoExport
    Scan(context, tDataList, settings.errorsMem, tOptions)
  File "C:\Users\Dave\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\decompose.py", line 2621, in Scan
    DecomposeMesh(scene, obj, tData, tOptions, errorsMem,obj.lodsetID>0)
  File "C:\Users\Dave\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\decompose.py", line 1886, in DecomposeMesh
    uv2_idx = mesh.urho_export.get_export_uv2()
  File "C:\Users\Dave\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\Urho3D_Blender\__init__.py", line 1045, in get_export_uv2
    return int(self.manual_uv2_idx)
ValueError: invalid literal for int() with base 10: ''`
 Do you think it is necessary to use Apply modifier when there is only an armature modifier? Applying that in Blender clears animations afaik. If not needed then there is no reason to continue, like you say, it is unlikely to fix the orientation problem (originally I thought it might). Though if it could help I can easily send the blend file.

Assuming the above is correct, then the armature can be rotated using an empty, without messing up animations? That sounds great, though I'm not sure how it could be done in code. The skeleton is a property of the AnimatedModel, and I would have thought any rotations would act on both objects. I'm also not sure how to do it in Blender.

**Comment by dertom95** [comment]
About "Apply Modifiers". I would(!) agree with your point of view that it should not be needed, but testing with one animation of mine showed a distored result of the result without using it. Not sure why....I usually have this option on.

> Though if it could help I can easily send the blend file.
Yeah,...do it. Then I can also have a look about the rotation problem....

**Comment by iBeta666** [comment]
Ok, thanks a lot. Anyway the 'Apply modifier' works now, so your fix did it!
I will e-mail the blend file.

**Comment by dertom95** [comment]
Just for completness(as I wrote it already via email). The wired rotation of the armature relative to the mesh was due to the mesh having rotation on the object. Applying this (mesh select,ctrl-a=>rotation)  fixed it.

**Comment by iBeta666** [comment]
Geez, my only excuse is that model has sent me temporarily (hopefully) insane. Anyway, thank you for sorting it out!  The model and animations are working fine now.

Have quickly looked at materials, and so far have not had any success. I'll keep trying tomorrow, but  have not been able to find  documentation. The Relativa build seems to use material lists, as do I from the fbx, but it seems you use nodetrees instead. What should I do if unsuccessful? It is nearly embarrassing to make 3 issues in 3 days :-) and this isn't even an issue.

**Comment by dertom95** [comment]
Well, I don't know how you load your model but at some place you have a model and can apply a material to it (I guess with something like SetMaterial(...) ). You can create this manually like others in your Data/Materials-Folder.
After blender's internal renderer got kicked (2.7->2.8?) I decided to implement the urho3d-materials as blender-nodetrees and add urho3d-preview selectable as blender-renderer (instead of e.g. cycles or eevee).  There is not really written documentation but some (outdated? at least good enough) videos (e.g: materials https://www.youtube.com/watch?v=13jslwWhUSk ).
Good luck

**Comment by iBeta666** [comment]
Fantastic.  Everything working now - thanks for your help, it has really helped.
