### ISSUE TITLE
Tree urho3dmaterials removed from EditorType Dropdown after Material Append

### ISSUE THREAD

**Issue by iBeta666** [dertom95/Urho3D-Blender#20]
Hi Dertom95,
After appending a procedural material from another blend file, any previously made composite material nodes are undefined and shown in red. This is likely due to the whole Tree urho3dmaterials EditorType being removed. Image below, this is reproducible. I can send the two blend files if required.

I'm a bit baffled, since it has worked fine when I have made my own procedural materials - I guess I could try to make it by hand instead of appending, but it is pretty complicated.
Thanks 

![Tree urho3dmaterials removed](https://user-images.githubusercontent.com/5455196/200316679-4fcfcf1d-d4cb-43de-b9e5-8fbc7f7a9604.jpg)

**Comment by dertom95** [comment]
Hmm,...what exactly do you mean with procedural material? Native Blender-Materials? And what is composite? (Urho3d Materials?). 
The problem in the screenshot is that for some reason the urho3d-nodetrees are not available at all. 

Make sure to set the Urho3D Exporter-Folder to some location (if you have links to textures or alike best to the same folder as the one that 'created' it) and export at least once. This will generate the correspondig nodetree  (DataFolder/__blender_material.json) and usually this path is set then automatically 

Some times this node tree is not loaded (not sure why) then you can manually set it.  To do this:
1) go to 'compositor-panel' 
![grafik](https://user-images.githubusercontent.com/389137/200327775-248b0069-3711-471c-bf2e-994476f4d090.png)

2) Then to the Urho3D-Tab on the right-tabs:
![grafik](https://user-images.githubusercontent.com/389137/200327925-a9ca9372-f22e-4fdc-87d4-ff7182f580d0.png)

3) Set Path to your DataFolder's __blender_material.json (uncheck relative path before 'accepting'-file): 
![grafik](https://user-images.githubusercontent.com/389137/200328342-daf4422c-7943-4189-b012-452ee3c3c583.png)

It should look like this:
![grafik](https://user-images.githubusercontent.com/389137/200328396-3fa940af-90e9-4b18-9845-19cdd5c9e683.png)

Then hit 'load json trees' and if everything went fine the nodes might(!) show up. 

I'm not 100% sure if the path you set manually is actually enforced by the exporter....it might be that it will be overwritten to the path of your data-folder.

To be honest I not 100% sure about how good appending/linking/reusing UrhoMaterial-Nodes is supported. At least cross-data-folder it might have issues.

Good luck. Plz try what I described. If that doesn't work you are welcome to send me your files and I will see what's going on after work

**Comment by iBeta666** [comment]
Ok, thanks. I should probably have made it clearer - I am not appending UrhoMaterial-Nodes, rather a procedural material made in the shading editor using nodes, as shown in screen shot below: 
 It (should) have nothing to do with the Urho3D nodes made in the compositor editor, but the Urho3D node trees just seem to get wiped out by the append. Btw, the material above does not cause problems. I will try your suggestions and see if I can get the Urho3D material node tree back.   


 On Monday, 7 November 2022 at 15:05:19 CET, Thomas Trocha ***@***.***> wrote:  
 
 


Hmm,...what exactly do you mean with procedural material? Native Blender-Materials? And what is composite? (Urho3d Materials?).
The problem in the screenshot is that for some reason the urho3d-nodetrees are not available at all.

Make sure to set the Urho3D Exporter-Folder to some location (if you have links to textures or alike best to the same folder as the one that 'created' it) and export at least once. This will generate the correspondig nodetree (DataFolder/__blender_material.json) and usually this path is set then automatically

Some times this node tree is not loaded (not sure why) then you can manually set it. To do this:
   
   -    
go to 'compositor-panel'   


   -    
Then to the Urho3D-Tab on the right-tabs:   


   -    
Set Path to your DataFolder's __blender_material.json (uncheck relative path before 'accepting'-file):   



It should look like this:


Then hit 'load json trees' and if everything went fine the nodes might(!) show up.

I'm not 100% sure if the path you set manually is actually enforced by the exporter....it might be that it will be overwritten to the path of your data-folder.

To be honest I not 100% sure about how good appending/linking/reusing UrhoMaterial-Nodes is supported. At least cross-data-folder it might have issues.

Good luck. Plz try what I described. If that doesn't work you are welcome to send me your files and I will see what's going on after work

**Comment by dertom95** [comment]
No problem. Glad I could help 👍
