### ISSUE TITLE
check if 'apply modifiers' can be make work again or remove or at least deactivate the option

### ISSUE THREAD

**Issue by dertom95** [dertom95/Urho3D-Blender#3]

**Comment by jforjustin** [comment]
Thanks for looking into this, as I use a lot of modifiers.
Possible workaround: use Alt+C to convert selected to mesh with modifiers, export, and revert.

**Comment by dertom95** [comment]
The modifier apply was actually working in matter of applying to the mesh, but it did not export uv-coords and some other vertex-data correctly..that should be fixed.

Hope that was the problem

**Comment by jforjustin** [comment]
Thanks for the fix to upstream issue which, while I was not inconvenienced, is great to have back as a feature. :)
