### ISSUE TITLE
Can't turn on latest version of Urho3D-Blender

### ISSUE THREAD

**Issue by lnarolski** [dertom95/Urho3D-Blender#9]
Hello,
I can't turn on the latest version of _Urho3D-Blender_ in Blender (v. 2.82.7 for Windows 10). I have enabled the latest version of _addon_jsonnodetree_ addon. Plugin from fd4bc10a2c0b4439ed3344ef7ebe4d435725abf9 commit (23 June 2019) is working fine.

Error I get:
![error](https://user-images.githubusercontent.com/44019588/78449957-5e196900-767b-11ea-971b-146abd76276b.png)

**Comment by dertom95** [comment]
you also need to activate blender-connect https://github.com/dertom95/addon_blender_connect hich will need you to install pyzmq in blender. This plugin will not work without pyzmq. 

**PLZ** use the release-pack in which all addons and the runtime including instructions 'how to install' are waiting!!!!  https://github.com/dertom95/Urho3D-Blender/releases/tag/0.1.2
